<?php
// 娛樂
return [
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "2月台股期指漲524點",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "陳時中預言失敗！增1境外從美國來",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "連4天「加零」止步 國內今新增1例境外移入",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "防疫保單賣翻　台產受理逾300萬件",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" => "百萬網紅「莫彩曦」獲「就業金卡」　可長住台灣",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "台股開高走高 收盤大漲559點飛越萬六",
    ],

    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "「小台積」ETF入手價親民　0052科技主題成分股7成為台積電",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "外媒曝螞蟻股權　中國紅二代涉投資",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "台股開紅盤！收16362點再創新高",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "台積電領軍 台股大漲559點收16362點創新高",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" =>  "台銀董座呂桔誠看牛年景氣　堅韌「牛轉乾坤」",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "牛年新春投資展望 法人看好台股延續多頭格局",
    ],

    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "超商領錢「ATM電話突狂響」 超糗真相曝",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "開紅盤破紀錄！台股盤中飆逾600點　站穩萬六",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "廣納候選疫苗？柯文哲：支持中央，台灣禁不起太多系統",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "晶技1月獲利將創新高 每股稅前賺0.84元",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" => "和碩與印度Tamil Nadu邦完成簽署MOU 印度廠估招募1.4萬名員工",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "斬政敵金脈！螞蟻IPO喊停內幕 傳潛在受益權貴是太子幫才是主因",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "永裕去年Q4純益可望季增雙位數 今年業績、獲利更上層樓",
    ],
    [
        "category" => "財經",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "開工＝財神降臨！5星座年後存款翻倍",
    ]
];