<?php
// 娛樂
return [
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "近3億人有抗體  專家認印度疫情已過最糟時期",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "小心！老年黃斑部病變「年輕化」　關鍵在於做了這可怕的事",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "慘了！「世紀瘟疫」死灰復燃　非洲已釀12例7死",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "英專家建議武肺典型症狀增至7項 疲倦腹瀉要注意",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" => "高市毒防局加碼醫療補助",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "食品標示新措施 上路",
    ],

    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "食物五味長期偏頗 影響五臟",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "奧克蘭COVID-19疫情未擴大 紐西蘭解除封鎖令",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "嬌生疫苗運抵南非  總統率先接種緩解民眾恐懼",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "美吾華攻生技有成　懷特乳癌新藥3月納健保",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" =>  "洗好了沒？車洗一半突倒地　心因性猝死",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "增1境外移入 台女返美前採檢確診",
    ],

    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "防疫新生活!春節腹瀉、類流感就診人次大降",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "不浪費AZ疫苗  南非將提供非洲其他國家使用",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "日本打了！4萬醫護接種輝瑞新冠疫苗",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "日本疫苗開打.拚奧運！首批輝瑞打4萬醫護",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" => "浩鼎主動免疫抗癌藥 申請南美非三國家臨床試驗",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "60國每周疫苗接種約4200萬劑　公衛學者估：全球疫情可望10月底解封",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "吉林疫情追查：推銷員辦講座 1傳141",
    ],
    [
        "category" => "健康",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "桃醫估2/19復工 國稅局擬降商家營業稅",
    ]
];