<?php
// 娛樂
return [
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "過季衣物先別丟！　迷你倉幫雜物找第二個「家」",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "開運靠這招！2021買3C先挑顏色",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "致命的PM2.5與懸浮微粒　這些日常可能傷害你的肺",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "共軍艦隊總數超越美軍　美趕製智慧無人戰機、自動軍艦壓制",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" => "海豹追媽媽不小心掉洞裡　「左搖右擺」卡裡面：救命！",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "體驗古代貴妃保養療程　她從頭叫到尾",
    ],

    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "路上外送情侶檔很常見？網抖2優勢",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "隔一天又中了！1.07億大樂透開這裡",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "快訊／大樂透1.07億元頭獎一注獨得 獎落台南市",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "工讀生「誤開80萬發票」　業者急：報錯限額用光了",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" =>  "台灣賭神戴子郎猝逝　除夕最後身影曝光",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "原來想要妹妹？家貓觀察小浪貓　竟主動邀牠「進屋」！",
    ],

    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "快訊／大樂透頭獎1.07億　台南開出1人獨得",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "秋冬專案將到期　陳時中：228後考慮放寬高鐵飲食、限縮政策擬採常態",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "過年衝動性消費買了啥？全場秒指它",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "交往小三1年半　前女友突傳訊「懷孕8個月」求幫付房租",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" => "春節宮廟香油錢可觀 紫南宮一年「還金」金額高達7億",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "4屁孩在衛武營生態池釣魚 喜炫戰利品合影點燃全網怒火",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "停車場柵欄不動！百萬名車女駕駛「拆車牌」　狂揮求感應引網友熱議",
    ],
    [
        "category" => "生活",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "朝天宮、奉天宮撞國運籤　暗指「安內必先攘外」？",
    ]
];