<?php
// 娛樂
return [
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "美中首熱線！拜登談台港　習冷回：是內政",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "趙少康：時隔25年重返台灣政壇的新聞人物"
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "LINE Pay除夕夜大當機！高市府、彰縣府回應了",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "美國制裁緬甸 英國考慮跟進",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" => "趙少康參選2024後 前扁辦主任爆戰國七雄名單：精彩",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "德國防疫封鎖延長至3月初 商界錯愕",
    ],

    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "賴神頭上動刀！理髮師分享理髮重點",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "德國延長全國防疫封鎖措施至3月7日 商界錯愕",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "印度防長：中印班公湖撤軍  回到2020對峙初",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "頂不住新德裡當局施壓  推特暫封印度部分賬戶",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" =>  "藍黨魁之爭暗潮洶湧 初三馬、江、趙有望同台",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "拜登令成立專案小組    檢討對中戰略",
    ],

    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "馬、江、趙初三合體？　李乾龍：廟都歡迎人來",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "黨魁之爭熱身 朱立倫年前勤跑地方打樁",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "「招財進寶」藏「自由民主」 外交部春聯風靡國外",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "印度防長證實 中印同意將進駐爭議邊境部隊後撤",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" => "拜登與習近平對話  陳以信：蔡總統機靈  超前部署",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "鄭文燦慰問桃醫值勤人員　預計年後分階段恢復營運",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "哈薩克反中情緒再引爆 中國領事館前接連示威",
    ],
    [
        "category" => "政治",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "拜登與習近平通話　中國國民黨：有助緩解區域緊張",
    ]
];