<?php
// 娛樂
return [
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "男被追殺願訣別「電話未通」斷氣　妻沒接到崩潰曝原因",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "北市市區出現未爆彈 警通報軍方帶回處理",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "北市資源回收驚見未爆彈 軍方移置處理",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "情侶吵架幫出頭　幫腔男遭痛毆慘失明",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" => "高雄水情緊張 降雨量較往年少5成",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "「互挺情侶」約談判！　男遭18人圍毆左眼失明",
    ],

    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "國五轎車自撞分隔島　駕駛噴車外身亡",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "過彎失控！丙烯車翻　開工日機捷一度停駛",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "虎尾交流道旁見衣服山 1/3馬路被霸占",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "瘋狂追殺！男被砍劫機車3貼逃命　仍遭衝撞奪命",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" =>  "彰化超旺彩券行 10天內開出2頭獎",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "黑衣女大鬧鹿港天后宮　亂丟金紙還狂踹香爐、供桌",
    ],

    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "高雄牛年小提燈 ｢牛揹揹｣時尚亮相",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "春雨未解南部旱情 嘉南啟動節水措施",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "死者生前開毒趴躲過警？　仇家譏笑引爆互砍",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "雲林民宅氣爆 獨居屋主身亡",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" => "無端捲仇殺案！ 2男大生驚恐載王男三貼逃命",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "「台灣賭神」戴子郎除夕夜心肌梗塞猝逝　享壽64歲",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "泰雅渡假村遭爆多項違法 創辦人之子控縣府包庇",
    ],
    [
        "category" => "社會地方",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "住戶投訴謝欣穎酒吧擾鄰　酒客吵到半夜",
    ]
];