<?php
// 娛樂
return [
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "SSA海事網絡研討會 24日登場",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "柬埔寨要引入「中國式」防火牆",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "來點正能量！CASETiFY推人氣插畫家Keigo聯名電子配件",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "Epic Games 針對 Apple 的反壟斷官司打到歐盟去了",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" => "日本與印度聯手合開發 6G 技術，預計2030年可以開始應用",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "iPhone 12 mini 銷量不似預期，但 Apple 似乎仍未放棄小屏幕！",
    ],

    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "臉書、蘋果衝突再加劇！祖克柏發起報復要員工讓Apple感受到痛苦",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "公益更需要效率　微軟工作坊助非營利組織導入Power Platform",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "微軟將協助測試 Xbox、PC 遊戲以改善其無障礙體驗",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "HUAWEI P50 系列下月如期發佈，依舊提供三款型號",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" =>  "【有影】內湖採草莓一日遊！初戀打卡款料理甜蜜登場",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "Clubhouse遭爆有中資背景 核心技術恐讓資料暴露給中國政府",
    ],

    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "Facebook 大戰蘋果，祖克柏告訴員工：「要讓蘋果感受痛苦」",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "宏碁智醫眼科AI輔助診斷軟體VeriSee DR 獲得泰國食藥局醫材許可證",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-3.png",
        "title" => "香港消委會氣炸鍋測試：貴不一定好",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-4.png",
        "title" => "北車疑用華為路由器 台鐵：只公告資訊且已拆除",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-6.png",
        "title" => "部桃抗體陰性可復工 擬試辦接觸者APP",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-9.png",
        "title" => "領到紅包、年終要怎花？編輯精選八大網購好物",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail.png",
        "title" => "Samsung Galaxy Book Ion2 輕盈到港",
    ],
    [
        "category" => "科技",
        "language_id" => 119,
        "locale_id" => 229,
        "photo" => "/assets/images/blog/post-thumbnail-2-1.png",
        "title" => "企業卡位！台中五期炙手可熱 去年破7筆億級交易",
    ]
];